apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec: 
  highAvailabilityController:
    enabled: true
    podTemplate:
      metadata:
        labels:
          pod-security.kubernetes.io/enforce: privileged
