---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: 1.17.5
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values

