apiVersion: batch/v1
kind: Job
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:9.3.0
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: vaultwarden-ic
              key: rootUser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vaultwarden-ic
              key: rootPassword
        - name: MYSQL_HOST
          value: "vaultwarden-ic"
        command: ["sh", "-c", "mysql -h $MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'CREATE DATABASE IF NOT EXISTS vaultwarden;'"]
      restartPolicy: Never
  backoffLimit: 4
