apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - innodb.yaml
  - initjob.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml
