apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - namespace.yaml
  - helmrepository.yaml
  - cm-values.yaml
  - helmrelease.yaml
  - ip-address-pool.yaml
  - l2-advertisement.yaml
