apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: cloudflare-tunnel-ingress-controller
spec:
  chart:
    spec:
      chart: cloudflare-tunnel-ingress-controller
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: strrl
        namespace: flux-system
      version: 0.1.0
  interval: 1m0s
