apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piraeus-operator
  namespace: piraeus-datastore
spec:
  chart:
    spec:
      chart: ./charts/piraeus
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: piraeus-operator
        namespace: flux-system
      version: 2.9.0
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: piraeus-operator-values

