apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql-operator
  namespace: mysql-operator
spec:
  chart:
    spec:
      chart: mysql-operator
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: mysql-operator
        namespace: flux-system
      version: 2.2.4
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: mysql-operator-values

