repositories:
  - name: mysql-operator
    url: https://mysql.github.io/mysql-operator/

releases:
  - name: "mysql"
    namespace: "demo-wordpress"
    chart: mysql-operator/mysql-innodbcluster
    version: 2.2.1
    values:
      - ./values.yaml
      - ./credentials.yaml
