apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-for-private
  namespace: cloudflare-tunnels
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.5.0
          args: [tunnel, --config, /etc/cloudflared/config/config.yaml, run]
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: k8s-private-tunnel-credential
        - name: config
          configMap:
            name: cloudflared-config-for-private
            items:
              - key: config.yaml
                path: config.yaml
      hostNetwork: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config-for-private
  namespace: cloudflare-tunnels
data:
  config.yaml: |-
    tunnel: k8s_private_tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    warp-routing:
      enabled: true
