apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-for-ssh
  namespace: cloudflare-tunnels
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.12.1
          args: [tunnel, --config, /etc/cloudflared/config/config.yaml, run]
          livenessProbe:
            httpGet:
              path: /ready
              port: 2001
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: k8s-ssh-tunnel-credential
        - name: config
          secret:
            secretName: k8s-ssh-tunnel-config
      hostNetwork: true
