---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-for-public
  namespace: cloudflare-tunnels
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.8.3
          args: [tunnel, --config, /etc/cloudflared/config/config.yaml, run]
          livenessProbe:
            httpGet:
              path: /ready
              port: 2002
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: k8s-public-tunnel-credential
        - name: config
          configMap:
            name: cloudflared-config-for-public
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config-for-public
  namespace: cloudflare-tunnels
data:
  config.yaml: |-
    tunnel: k8s_public_tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2002
    no-autoupdate: true
    ingress:
    - hostname: test.maesh.dev
      service: https://google.com
    - hostname: www.maesh.dev
      service: hello_world
    - service: http_status:404
