apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-wordpress-wp-php-config
  namespace: demo-wordpress
data:
  uploads.ini: |-
    file_uploads = On
    upload_max_filesize = 256M
    post_max_size = 256M
    max_execution_time = 600
