apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-wordpress
  namespace: demo-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-wordpress
  template:
    metadata:
      labels:
        app: demo-wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.6.2
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
          volumeMounts:
            - name: php-config
              subPath: uploads.ini
              mountPath: /usr/local/etc/php/conf.d/uploads.ini
          env:
          - name: WORDPRESS_DB_HOST
            value: innodb:6446
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: demo-wordpress-ic
                key: rootPassword
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: demo-wordpress-ic
                key: rootUser
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: pvc-demo-wordpress
      volumes:
        - name: php-config
          configMap:
            name: demo-wordpress-wp-php-config 
            defaultMode: 420
