apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: innodb
  namespace: demo-wordpress
spec:
  instances: 3
  version: "9.0.1"
  tlsUseSelfSigned: true
  secretName: demo-wordpress-ic
  router:
    instances: 1
    version: "9.0.1"
  datadirVolumeClaimTemplate:
    storageClassName: nfs-client
    accessModes: 
      - "ReadWriteOnce"
    resources:
      requests:
        storage: "10Gi"
