apiVersion: batch/v1
kind: Job
metadata:
  name: demo-wordpress-ic
  namespace: demo-wordpress
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:9.0.1
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: demo-wordpress-ic
              key: rootUser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-wordpress-ic
              key: rootPassword
        - name: MYSQL_HOST
          value: "innodb"
        command: ["sh", "-c", "mysql -h $MYSQL_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'CREATE DATABASE IF NOT EXISTS wordpress;'"]
      restartPolicy: Never
  backoffLimit: 4

