apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo-wordpress
  namespace: demo-wordpress
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
