apiVersion: v1
kind: Service
metadata:
  name: demo-wordpress
  namespace: demo-wordpress
spec:
  selector:
    app: demo-wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

