apiVersion: v1
data:
    account_id: ENC[AES256_GCM,data:WqiktzqIHNi3XVmJCuTv4KKJ64wYzIDyrvjp8YhP+XxnREVTmGJClLITQUk=,iv:GEUcuW7Oh+cCdUTLHlUfxLY2RexrRKJ/7cFd5XWBIJw=,tag:cUAinEHHs1aieFP22JHCsg==,type:str]
    api_token: ENC[AES256_GCM,data:cV+9PW3c0HUQllD5et7hl7Pb3l8YYtl96SAA+74wxXGU6uObn9q+D0BMIMqJoqMbgLDltHvHAcI=,iv:QZdG9x3UpBMOC8uvBPg2Y7OQ03i9cFzl4QRp4sLSB/o=,tag:aDFcM+GA39L8Hu8tU0o9zQ==,type:str]
    tunnel_name: ENC[AES256_GCM,data:7nBoBWo+KH4voSsiB2/ODUH5RMQSxcDlOplARA==,iv:ee12H/11lK/8WqXD3X/ZjpamAlARm9vZX5km7e5yBbY=,tag:Zv59YLfIV3fLPdHXQrnaGw==,type:str]
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: integrated-ingress-controller
type: Opaque
sops:
    lastmodified: "2025-07-17T15:02:51Z"
    mac: ENC[AES256_GCM,data:tiTEMp+oJHEw5bVB1lwyeUUyhq9XRbl+PAwrrIfYUaSB3kOtHMKIqCmEz+602SwVvCPiMc70R2LHZlyDsF7l/DS7feWlWPCwicP4GB03npofCdSaXWLAnj0CXoydyoRPLHgxwpu7aDYNjjxVopZO6asBHaXqEt7+C1Ru2fHW/KM=,iv:bmEo7u1TQcxEH0YbCSUV61ZrWv4Om63/LqQ3+CEfTQs=,tag:JMDAMTskO8cczZgFYhuRpw==,type:str]
    pgp:
        - created_at: "2025-07-17T15:02:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7FRUASef4xJAQ/7BabS3+Po11F4WweTRIv7IxmeWggHdryWC90zNQIOqDQX
            eOqi3BKCoiBZiT1e/ipJyV2zKQuN8NoENteeiJcTMayC+6CG7fG8GcjMWDoWyufd
            yxN3dcw+KHsFW/wzuQtsJyaCUNDBsCRUbRXXRLdpyzd9PUopHxpl92u7KDBIVtmy
            nnJbfzcMHVvzFKcbBGGgsSlwPb85uJggPQoT8A0rXRJEEW90X3T+JJmYIyRI4dfc
            1HJiYLcjN8m/Gj8uCVGeoZBU7UOSt+sY+Reoha1KaxhMt0G+Lbu+KaV436nPBgkv
            3I4t1/hJ1bdqZkODGebpw5svrxpsGuPt1ZCKjK3ka5dGO/rJVKXg/sER+vu5Orcz
            zIdNqMOp6v9bcvlXTOaJ/4U2EW+vWYRAIN+Qq9Zq7sZ6He0Z58eiYhjwchcN0sdv
            H6lVscZMuK/ejJVW5gfGx54p38LDZV9QaYMM9wHDJ0OMOy+EndxP2GShM5JrN/H6
            75+5OiAEz4gneEK/b328+3iBryFj4XNGZ3enEkCzEXX7gFsuZG9EBJ2EaI128xHi
            LDNmQuKWEJyZdM2I5faA9zFo7HZMCivwNwij+LyZT0tsBDd56tR2nC7KDFecfwRp
            mskVhTCsIVtjBUCX3jNbTMeh7luX3HYeTvtxOApBG4rFo1mm2HmKoP8dXNOnWhXS
            XAH5XMdscAzojF4iGE/jku5thCi/QFPq2kEnoCeHE+K39Gld1By43W8VeX0ELt1N
            mD8aiN3nB/g5sejCSAjNBXyy+c7soPJSgtiEVPwrBrqr9pQGJ5+bmb4jVwb5
            =cfsr
            -----END PGP MESSAGE-----
          fp: 3F5D70BDF31E7C71F9E32ED2A22AC945D4461182
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
