apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: integrated-ingress-controller
  namespace: integrated-ingress-controller
spec:
  chart:
    spec:
      chart: integrated-ingress
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: integrated-ingress-controller
        namespace: flux-system
      version: 0.2.5
  interval: 1m0s
