apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: integrated-ingress-controller
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://maeshinshin.github.io/integrated-ingress-controller
