apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  name: vm1
  namespace: vms
spec:
  dataVolumeTemplates:
    - metadata:
        name: vm1
      spec:
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: nfs-client
        source:
          http:
            url: https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2
  instancetype:
    name: t-4096
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices:
          disks:
          - name: disk0
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: vm1
        name: disk0
      - cloudInitConfigDrive:
          secretRef:
            name: vm1-cloud-init
        name: cloudinitdisk
status: {}
