apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  name: vm3
  namespace: vms
spec:
  dataVolumeTemplates:
    - metadata:
        name: vm3
      spec:
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: nfs-client
        source:
          pvc:
            name: ubuntu-2204
            namespace: vms
  instancetype:
    name: t-2048
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
      labels:
        vm: vm3
    spec:
      domain:
        devices:
          disks:
          - name: disk0
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: vm3
        name: disk0
      - cloudInitConfigDrive:
          secretRef:
            name: vm3-cloud-init
        name: cloudinitdisk
status: {}
