apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: piraeus-operator
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/piraeusdatastore/piraeus-operator
  ref:
    branch: v2
