apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  creationTimestamp: null
  name: f-8192
  namespace: vms
spec:
  cpu:
    guest: 4
  memory:
    guest: 8Gi
