apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterInstancetype
metadata:
  creationTimestamp: null
  name: o-256
  namespace: vms
spec:
  cpu:
    guest: 1
  memory:
    guest: 256Mi
