apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  creationTimestamp: null
  name: sock
  namespace: test
  namespace: vms
spec:
  cpu:
    preferredCPUTopology: preferSockets
