apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: growi-manager
  namespace: growi-system
spec:
  chart:
    spec:
      chart: growi-manager
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: growi-manager
        namespace: flux-system
      version: 0.2.3
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: growi-manager-values
