apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: growi-manager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/growi-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
