apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: growi
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/growi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
