apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/piraeus-operator/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linstorcluster
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/piraeus-operator/linstorcluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: piraeus-operator-controller-manager
      namespace: piraeus-datastore
