---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.346.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: helm/helm@v3.17.3
- name: helmfile/helmfile@v0.171.0
