repositories:
  - name: mysql-operator
    url: https://mysql.github.io/mysql-operator/

releases:
  - name: crds-mysql-operator
    namespace: my-mysql-operator
    chart: ../../manifests/crds/mysql-operator
  - name: mysql-operator
    namespace: my-mysql-operator
    chart: mysql-operator/mysql-operator
    version: 2.2.2
    values:
      - ./values.yaml
