repositories:
  - name: mysql-operator
    url: https://mysql.github.io/mysql-operator/

releases:
  - name: "mysql-operator"
    namespace: "my-mysql-operator"
    chart: mysql-operator/mysql-operator
    version: 2.2.1
    values:
      - ./values.yaml
