repositories:
  - name: mysql-operator
    url: https://mysql.github.io/mysql-operator/

releases:
  - name: "mysql"
    namespace: "vaultwarden"
    chart: mysql-operator/mysql-innodbcluster
    version: 2.2.2
    values:
      - ./values.yaml
      - ./credentials.yaml
